### ISSUE TITLE
Request: Add instructions + submit to fdroid

### ISSUE THREAD

**Issue by klundry** [koreader/android-send2ebook#1]
I think some build/install instructions are needed since there is not a APK file provided.

Also, it would be great to have the app available on the fdroid store.

**Comment by Frenzie** [comment]
@mwoz123 included some apks inside the repo

https://github.com/koreader/android-send2ebook/tree/master/repo

I added the latest file to the releases tag.

**Comment by klundry** [comment]
Thanks for that! It immediately crashes for me though. I'm on LineageOS/android version 8.1 without google services.

**Comment by Frenzie** [comment]
Sorry, I don't really know much about it since my usage normally doesn't include downloading files on my phone.
